services:
  trufor:
    build: 
      context: ../models/trufor
      dockerfile: Dockerfile
    image: trufor
    volumes:
      - ./model_outputs/trufor:/model_outputs/trufor
      - ./saved_photo:/saved_photo